// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum RoundStateType {
  COMMIT,
  REVEAL
}

enum GameStateType {
  NOT_STARTED,
  IN_PROGRESS,
  FINISHED
}
