// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { RoundIndex, RoundIndexTableId } from "./tables/RoundIndex.sol";
import { Rounds, RoundsData, RoundsTableId } from "./tables/Rounds.sol";
import { Players, PlayersTableId } from "./tables/Players.sol";
import { PlayersCount, PlayersCountTableId } from "./tables/PlayersCount.sol";
import { Commitments, CommitmentsTableId } from "./tables/Commitments.sol";
import { GameState, GameStateTableId } from "./tables/GameState.sol";
import { Owner, OwnerTableId } from "./tables/Owner.sol";
import { CommitDuration, CommitDurationTableId } from "./tables/CommitDuration.sol";
import { RevealDuration, RevealDurationTableId } from "./tables/RevealDuration.sol";
import { RoundCount, RoundCountTableId } from "./tables/RoundCount.sol";
